# Generated by Django 6.0.5 on 2026-05-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotecas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('quantidade', models.IntegerField(default=1)),
                ('disponivel', models.BooleanField(default=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='bibliotecas.biblioteca')),
            ],
        ),
    ]
