# Generated by Django 5.2.14 on 2026-06-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20),
        ),
    ]
