# Generated by Django 5.2.14 on 2026-06-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('romance', 'Romance'), ('ficcao_cientifica', 'Ficção Científica'), ('historia', 'História'), ('autoajuda', 'Autoajuda'), ('biografia', 'Biografia'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
    ]
