# Generated by Django 5.2.14 on 2026-06-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('leitor', 'Leitor'), ('bibliotecario', 'Bibliotecário'), ('admin', 'Administrador')], default='leitor', max_length=20),
        ),
    ]
