# Generated by Django 6.0.5 on 2026-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('emprestado', 'Emprestado'), ('devolvido', 'Devolvido')], default='pendente', max_length=20),
        ),
    ]
