# Generated by Django 5.2.14 on 2026-06-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
        ('emprestimos', '0002_alter_emprestimo_status'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doador', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=1)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='bibliotecas.biblioteca')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='livros.livro')),
            ],
        ),
    ]
