# Generated by Django 5.2.14 on 2026-06-10 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
        ('emprestimos', '0003_doacao'),
        ('livros', '0003_livro_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('meta', models.IntegerField(default=1, help_text='Quantidade de livros a ler')),
                ('data_fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='bibliotecas.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('votos', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='bibliotecas.biblioteca')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvisoDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('notificado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='livros.livro')),
            ],
            options={
                'unique_together': {('livro', 'leitor')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livros_lidos', models.IntegerField(default=0)),
                ('concluido', models.BooleanField(default=False)),
                ('data_participacao', models.DateTimeField(auto_now_add=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='emprestimos.desafio')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_participando', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('desafio', 'leitor')},
            },
        ),
        migrations.CreateModel(
            name='VotoSugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sugestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='emprestimos.sugestao')),
            ],
            options={
                'unique_together': {('sugestao', 'leitor')},
            },
        ),
    ]
